### ISSUE TITLE
Stop At Last Page

### ISSUE THREAD

**Issue by ErAshu** [nitingohel/NGIntroView-SWIFT3#1]
can you please tell me how to stop at last page until press skip.

**Comment by nitingohel** [comment]
you can do code on skip button for the jump to last page.

**Comment by ErAshu** [comment]
I think you don't understand the issue. I don't want to swipe right to left if i reached at last page. This time when i swipe this disappeared.

**Comment by nitingohel** [comment]
in **LoadIntro** method you need to add one property called like that.

> introView?.swipeToExit = false

that will be stop finish on last page

**Comment by ErAshu** [comment]
Thanks Nitin... It works.
